# Generated by Django 2.0.5 on 2018-05-13 17:38

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Название Задачи', max_length=100)),
                ('description', models.TextField(help_text='Описание Задачи', max_length=250)),
                ('date', models.DateField(default=datetime.date(2018, 6, 3))),
                ('priority', models.CharField(choices=[('H', 'Высокий'), ('M', 'Средний'), ('L', 'Низкий')], default='M', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
