# Generated by Django 2.0.5 on 2018-05-14 17:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('COMP', 'Выполнено'), ('IP', 'В процессе'), ('NCOM', 'Не выполнено')], default='NCOM', max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateField(default=datetime.date(2018, 6, 4)),
        ),
    ]
