# Generated by Django 2.0.5 on 2018-05-14 18:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManager', '0002_auto_20180514_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateField(default=datetime.date(2018, 5, 15)),
        ),
    ]
