# Generated by Django 2.0.5 on 2018-05-15 16:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManager', '0003_auto_20180514_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateField(default=datetime.date(2018, 5, 16)),
        ),
    ]
